def CreateMaterialDict():
        MaterialDict={}
        MaterialDict[1]="apartments"
        MaterialDict[2]="barracks"
        MaterialDict[3]="dormitory"
        MaterialDict[4]="farm"
        MaterialDict[5]="hotel"
        MaterialDict[6]="house"
        MaterialDict[7]="residential"
        MaterialDict[8]="commercial"
        MaterialDict[9]="industrial"
        MaterialDict[10]="kiosk"
        MaterialDict[11]="office"
        MaterialDict[12]="supermarket"
        MaterialDict[13]="cathedral"
        MaterialDict[14]="church"
        MaterialDict[15]="monastery"
        MaterialDict[16]="mosque"
        MaterialDict[17]="religious"
        MaterialDict[18]="shrine"
        MaterialDict[19]="synagogue"
        MaterialDict[20]="temple"
        MaterialDict[21]="college"
        MaterialDict[22]="fire_station"
        MaterialDict[23]="hospital"
        MaterialDict[24]="school"
        MaterialDict[25]="university"
        MaterialDict[26]="garage"
        return MaterialDict

